CREATE TABLE Role (
    roleID INT AUTO_INCREMENT PRIMARY KEY,
    roleName VARCHAR(20) NOT NULL UNIQUE,
    roleNumber INT NOT NULL UNIQUE
);

INSERT INTO Role (roleName, roleNumber) VALUES
    ('seller', 1),
    ('bidder', 2),
    ('admin', 3);

CREATE TABLE User (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(120) NOT NULL UNIQUE,
    Password VARCHAR(200) NOT NULL,
    roleID INT NOT NULL,
    FOREIGN KEY (roleID) REFERENCES Role(roleID)
);

CREATE TABLE Seller (
    USERID INT PRIMARY KEY,
    FOREIGN KEY (USERID) REFERENCES User(USERID)
);

CREATE TABLE Bidder (
    USERID INT PRIMARY KEY,
    FOREIGN KEY (USERID) REFERENCES User(USERID)
);

CREATE TABLE Admin (
    USERID INT PRIMARY KEY,
    FOREIGN KEY (USERID) REFERENCES User(USERID)
);

CREATE TABLE Item (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    startingPrice DECIMAL(10,2) NOT NULL,
    endTime DATETIME NOT NULL,
    isAuctionActive BOOLEAN DEFAULT TRUE,
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES Seller(USERID)
);

CREATE TABLE Bid (
    bidID INT AUTO_INCREMENT PRIMARY KEY,
    itemID INT NOT NULL,
    userID INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    bidTime DATETIME NOT NULL,
    FOREIGN KEY (itemID) REFERENCES Item(ItemID),
    FOREIGN KEY (userID) REFERENCES Bidder(USERID)
);